version: "3.8" # specifying version to avoid any compatibility issues | newer versions doesn't require version to be specified

services:
    app:
        build:
            context: ./candidate-api
            dockerfile: Dockerfile
        container_name: candidate_api
        tty: true
        restart: unless-stopped
        mem_limit: 768m
        mem_reservation: 768m
        volumes:
            - ./candidate-api:/var/www:delegated
        healthcheck:
            test: pidof php-fpm
            interval: 1s
            timeout: 1s
            retries: 60
        depends_on:
            postgres:
                condition: service_healthy
        links:
            - postgres:postgres
        networks:
            - sparkhire_challenge

    nginx:
        image: nginx:alpine
        container_name: nginx
        tty: true
        mem_limit: 128m
        mem_reservation: 128m
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./candidate-api:/var/www:delegated
            - ./candidate-api/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - sparkhire_challenge

    postgres:
        image: postgres:16.3
        container_name: postgres
        environment:
            POSTGRES_DB: sparkhire_challenge
            POSTGRES_USER: sparkhire
            POSTGRES_PASSWORD: sparkhire
        volumes:
            - ./postgres_data:/var/lib/postgresql/data:delegated
        ports:
            - "5432:5432"
        healthcheck:
            test:
                ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
            interval: 30s
            timeout: 10s
            retries: 5
        networks:
            - sparkhire_challenge

    client:
        container_name: candidate_client
        image: candidate_client
        build:
            context: ./candidate-client
            dockerfile: Dockerfile
            target: deploy-node
        ports:
            - 3000:3000
        restart: unless-stopped
        networks:
            - sparkhire_challenge

networks:
    sparkhire_challenge:
        driver: bridge

volumes:
    postgres_data:
        driver: local
